name: Elixir CI
env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3 # Define the elixir version [required]
        otp-version: 22.2.3 # Define the OTP version [required]

    - name: Install Dependencies
      run: mix deps.get

    - name: Build
      run: mix compile

    - name: Lint
      run: mix credo

    - name: Run Tests
      run: mix coveralls.github
